### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by nbdy** [nknorg/nkn-sdk-py3#10]
- website states that this repo is managed by the core team
- but there have not been any commits in 4 years 
- it does not have any of the features the go sdk has
- what happened to issue 1-6

**Comment by yilunzhang** [comment]
The wallet part of the sdk (transaction, etc) is still maintained and used internally in our system, but we didn't implement the client part of the sdk (send/receive message, session, etc). Any help would be appreciated.

**Comment by nbdy** [comment]
Thanks for the response.

When I have the time I'll contribute.
The golang SDK works great and should be a good reference.
